In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\juypterNoteBook\Machine learing\collage\adult.csv')
df.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K

In [3]:
df.head()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

(48842, 15)

In [4]:
import numpy as np
df.replace('?', np.nan, inplace=True)

In [5]:
df.isnull().sum()
df.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [6]:
df['workclass'].fillna(df['workclass'].mode()[0], inplace=True)
df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)
df['native-country'].fillna(df['native-country'].mode()[0], inplace=True)

C:\Users\97abh\AppData\Local\Temp\ipykernel_13752\1006053529.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['workclass'].fillna(df['workclass'].mode()[0], inplace=True)
C:\Users\97abh\AppData\Local\Temp\ipykernel_13752\1006053529.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)
C:\Users\97abh\AppData\Local\Temp\ipykernel_13752\1006053529.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['native-country'].fillna(df['native-country'].mode()[0], inplace=True)

In [7]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [8]:
df['income'] = df['income'].map({'<=50K':0, '>50K':1})

In [9]:
df = pd.get_dummies(df, drop_first=True)

In [10]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 98 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        48842 non-null  int64
 1   fnlwgt                                     48842 non-null  int64
 2   educational-num                            48842 non-null  int64
 3   capital-gain                               48842 non-null  int64
 4   capital-loss                               48842 non-null  int64
 5   hours-per-week                             48842 non-null  int64
 6   income                                     48842 non-null  int64
 7   workclass_Local-gov                        48842 non-null  bool
 8   workclass_Never-worked                     48842 non-null  bool
 9   workclass_Private                          48842 non-null  bool
 10  workclass_Self-emp-inc                     48842 non-null  bool
 11  workclass_Self-emp-not-inc                 48842 non-null  bool
 12  workclass_State-gov                        48842 non-null  bool
 13  workclass_Without-pay                      48842 non-null  bool
 14  education_11th                             48842 non-null  bool
 15  education_12th                             48842 non-null  bool
 16  education_1st-4th                          48842 non-null  bool
 17  education_5th-6th                          48842 non-null  bool
 18  education_7th-8th                          48842 non-null  bool
 19  education_9th                              48842 non-null  bool
 20  education_Assoc-acdm                       48842 non-null  bool
 21  education_Assoc-voc                        48842 non-null  bool
 22  education_Bachelors                        48842 non-null  bool
 23  education_Doctorate                        48842 non-null  bool
 24  education_HS-grad                          48842 non-null  bool
 25  education_Masters                          48842 non-null  bool
 26  education_Preschool                        48842 non-null  bool
 27  education_Prof-school                      48842 non-null  bool
 28  education_Some-college                     48842 non-null  bool
 29  marital-status_Married-AF-spouse           48842 non-null  bool
 30  marital-status_Married-civ-spouse          48842 non-null  bool
 31  marital-status_Married-spouse-absent       48842 non-null  bool
 32  marital-status_Never-married               48842 non-null  bool
 33  marital-status_Separated                   48842 non-null  bool
 34  marital-status_Widowed                     48842 non-null  bool
 35  occupation_Armed-Forces                    48842 non-null  bool
 36  occupation_Craft-repair                    48842 non-null  bool
 37  occupation_Exec-managerial                 48842 non-null  bool
 38  occupation_Farming-fishing                 48842 non-null  bool
 39  occupation_Handlers-cleaners               48842 non-null  bool
 40  occupation_Machine-op-inspct               48842 non-null  bool
 41  occupation_Other-service                   48842 non-null  bool
 42  occupation_Priv-house-serv                 48842 non-null  bool
 43  occupation_Prof-specialty                  48842 non-null  bool
 44  occupation_Protective-serv                 48842 non-null  bool
 45  occupation_Sales                           48842 non-null  bool
 46  occupation_Tech-support                    48842 non-null  bool
 47  occupation_Transport-moving                48842 non-null  bool
 48  relationship_Not-in-family                 48842 non-null  bool
 49  relationship_Other-relative                48842 non-null  bool
 50  relationship_Own-child                     48842 non-null  bool
 51  relationship_Unmarried                     48842 non-null  bool
 52  relationship_Wife                          48842 non-null  bool
 53  race_Asian-Pac-Islander                    48842 non-null  bool
 54  race_Black                                 48842 non-null  bool
 55  race_Other                                 48842 non-null  bool
 56  race_White                                 48842 non-null  bool
 57  gender_Male                                48842 non-null  bool
 58  native-country_Canada                      48842 non-null  bool
 59  native-country_China                       48842 non-null  bool
 60  native-country_Columbia                    48842 non-null  bool
 61  native-country_Cuba                        48842 non-null  bool
 62  native-country_Dominican-Republic          48842 non-null  bool
 63  native-country_Ecuador                     48842 non-null  bool
 64  native-country_El-Salvador                 48842 non-null  bool
 65  native-country_England                     48842 non-null  bool
 66  native-country_France                      48842 non-null  bool
 67  native-country_Germany                     48842 non-null  bool
 68  native-country_Greece                      48842 non-null  bool
 69  native-country_Guatemala                   48842 non-null  bool
 70  native-country_Haiti                       48842 non-null  bool
 71  native-country_Holand-Netherlands          48842 non-null  bool
 72  native-country_Honduras                    48842 non-null  bool
 73  native-country_Hong                        48842 non-null  bool
 74  native-country_Hungary                     48842 non-null  bool
 75  native-country_India                       48842 non-null  bool
 76  native-country_Iran                        48842 non-null  bool
 77  native-country_Ireland                     48842 non-null  bool
 78  native-country_Italy                       48842 non-null  bool
 79  native-country_Jamaica                     48842 non-null  bool
 80  native-country_Japan                       48842 non-null  bool
 81  native-country_Laos                        48842 non-null  bool
 82  native-country_Mexico                      48842 non-null  bool
 83  native-country_Nicaragua                   48842 non-null  bool
 84  native-country_Outlying-US(Guam-USVI-etc)  48842 non-null  bool
 85  native-country_Peru                        48842 non-null  bool
 86  native-country_Philippines                 48842 non-null  bool
 87  native-country_Poland                      48842 non-null  bool
 88  native-country_Portugal                    48842 non-null  bool
 89  native-country_Puerto-Rico                 48842 non-null  bool
 90  native-country_Scotland                    48842 non-null  bool
 91  native-country_South                       48842 non-null  bool
 92  native-country_Taiwan                      48842 non-null  bool
 93  native-country_Thailand                    48842 non-null  bool
 94  native-country_Trinadad&Tobago             48842 non-null  bool
 95  native-country_United-States               48842 non-null  bool
 96  native-country_Vietnam                     48842 non-null  bool
 97  native-country_Yugoslavia                  48842 non-null  bool
dtypes: bool(91), int64(7)
memory usage: 6.8 MB

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,25,226802,7,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,38,89814,9,0,0,50,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,28,336951,12,0,0,40,1,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,44,160323,10,7688,0,40,1,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,18,103497,10,0,0,30,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ['age','educational-num','capital-gain','capital-loss','hours-per-week']
df[num_cols] = scaler.fit_transform(df[num_cols])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 98 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        48842 non-null  float64
 1   fnlwgt                                     48842 non-null  int64
 2   educational-num                            48842 non-null  float64
 3   capital-gain                               48842 non-null  float64
 4   capital-loss                               48842 non-null  float64
 5   hours-per-week                             48842 non-null  float64
 6   income                                     48842 non-null  int64
 7   workclass_Local-gov                        48842 non-null  bool
 8   workclass_Never-worked                     48842 non-null  bool
 9   workclass_Private                          48842 non-null  bool
 10  workclass_Self-emp-inc                     48842 non-null  bool
 11  workclass_Self-emp-not-inc                 48842 non-null  bool
 12  workclass_State-gov                        48842 non-null  bool
 13  workclass_Without-pay                      48842 non-null  bool
 14  education_11th                             48842 non-null  bool
 15  education_12th                             48842 non-null  bool
 16  education_1st-4th                          48842 non-null  bool
 17  education_5th-6th                          48842 non-null  bool
 18  education_7th-8th                          48842 non-null  bool
 19  education_9th                              48842 non-null  bool
 20  education_Assoc-acdm                       48842 non-null  bool
 21  education_Assoc-voc                        48842 non-null  bool
 22  education_Bachelors                        48842 non-null  bool
 23  education_Doctorate                        48842 non-null  bool
 24  education_HS-grad                          48842 non-null  bool
 25  education_Masters                          48842 non-null  bool
 26  education_Preschool                        48842 non-null  bool
 27  education_Prof-school                      48842 non-null  bool
 28  education_Some-college                     48842 non-null  bool
 29  marital-status_Married-AF-spouse           48842 non-null  bool
 30  marital-status_Married-civ-spouse          48842 non-null  bool
 31  marital-status_Married-spouse-absent       48842 non-null  bool
 32  marital-status_Never-married               48842 non-null  bool
 33  marital-status_Separated                   48842 non-null  bool
 34  marital-status_Widowed                     48842 non-null  bool
 35  occupation_Armed-Forces                    48842 non-null  bool
 36  occupation_Craft-repair                    48842 non-null  bool
 37  occupation_Exec-managerial                 48842 non-null  bool
 38  occupation_Farming-fishing                 48842 non-null  bool
 39  occupation_Handlers-cleaners               48842 non-null  bool
 40  occupation_Machine-op-inspct               48842 non-null  bool
 41  occupation_Other-service                   48842 non-null  bool
 42  occupation_Priv-house-serv                 48842 non-null  bool
 43  occupation_Prof-specialty                  48842 non-null  bool
 44  occupation_Protective-serv                 48842 non-null  bool
 45  occupation_Sales                           48842 non-null  bool
 46  occupation_Tech-support                    48842 non-null  bool
 47  occupation_Transport-moving                48842 non-null  bool
 48  relationship_Not-in-family                 48842 non-null  bool
 49  relationship_Other-relative                48842 non-null  bool
 50  relationship_Own-child                     48842 non-null  bool
 51  relationship_Unmarried                     48842 non-null  bool
 52  relationship_Wife                          48842 non-null  bool
 53  race_Asian-Pac-Islander                    48842 non-null  bool
 54  race_Black                                 48842 non-null  bool
 55  race_Other                                 48842 non-null  bool
 56  race_White                                 48842 non-null  bool
 57  gender_Male                                48842 non-null  bool
 58  native-country_Canada                      48842 non-null  bool
 59  native-country_China                       48842 non-null  bool
 60  native-country_Columbia                    48842 non-null  bool
 61  native-country_Cuba                        48842 non-null  bool
 62  native-country_Dominican-Republic          48842 non-null  bool
 63  native-country_Ecuador                     48842 non-null  bool
 64  native-country_El-Salvador                 48842 non-null  bool
 65  native-country_England                     48842 non-null  bool
 66  native-country_France                      48842 non-null  bool
 67  native-country_Germany                     48842 non-null  bool
 68  native-country_Greece                      48842 non-null  bool
 69  native-country_Guatemala                   48842 non-null  bool
 70  native-country_Haiti                       48842 non-null  bool
 71  native-country_Holand-Netherlands          48842 non-null  bool
 72  native-country_Honduras                    48842 non-null  bool
 73  native-country_Hong                        48842 non-null  bool
 74  native-country_Hungary                     48842 non-null  bool
 75  native-country_India                       48842 non-null  bool
 76  native-country_Iran                        48842 non-null  bool
 77  native-country_Ireland                     48842 non-null  bool
 78  native-country_Italy                       48842 non-null  bool
 79  native-country_Jamaica                     48842 non-null  bool
 80  native-country_Japan                       48842 non-null  bool
 81  native-country_Laos                        48842 non-null  bool
 82  native-country_Mexico                      48842 non-null  bool
 83  native-country_Nicaragua                   48842 non-null  bool
 84  native-country_Outlying-US(Guam-USVI-etc)  48842 non-null  bool
 85  native-country_Peru                        48842 non-null  bool
 86  native-country_Philippines                 48842 non-null  bool
 87  native-country_Poland                      48842 non-null  bool
 88  native-country_Portugal                    48842 non-null  bool
 89  native-country_Puerto-Rico                 48842 non-null  bool
 90  native-country_Scotland                    48842 non-null  bool
 91  native-country_South                       48842 non-null  bool
 92  native-country_Taiwan                      48842 non-null  bool
 93  native-country_Thailand                    48842 non-null  bool
 94  native-country_Trinadad&Tobago             48842 non-null  bool
 95  native-country_United-States               48842 non-null  bool
 96  native-country_Vietnam                     48842 non-null  bool
 97  native-country_Yugoslavia                  48842 non-null  bool
dtypes: bool(91), float64(5), int64(2)
memory usage: 6.8 MB

In [14]:
df.head()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,-0.995129,226802,-1.197259,-0.144804,-0.217127,-0.034087,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,-0.046942,89814,-0.419335,-0.144804,-0.217127,0.772930,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,-0.776316,336951,0.747550,-0.144804,-0.217127,-0.034087,1,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0.390683,160323,-0.030373,0.886874,-0.217127,-0.034087,1,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,-1.505691,103497,-0.030373,-0.144804,-0.217127,-0.841104,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False